theme: jekyll-theme-leap-day
title: [Sanchez FC]
description: [Hey welcome to my house. This is where I post some fun stuffs.]

plugins:
  - jemoji
  - jekyll-remote-theme
url: "https://97007kim.github.io/"
markdown: kramdown
