remote_theme: pages-themes/tactile@v0.2.0
title: [Sanchez FC]
description: [Watch me whip, watch me nae nae]

plugins:
  - jemoji
  - jekyll-remote-theme
url: "https://97007kim.github.io/"
markdown: kramdown
